import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import React from "react"
import ToDoList from '@/components/todolist'

import { useReducer } from "react";
import { MainContext } from "@/states/";
import { initialState } from "@/states";
import { mainReducer } from "@/states/reducers";
import Navbar from '@/components/navbar/Navbar';



export default function Home() {
  const [state, dispatch] = useReducer(mainReducer, initialState);

  return (
    <>
      <Head>
        <title>Next - Global State in a TodoList</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContext.Provider value={{ state, dispatch }}>
        <main className={`${styles.Home}`}>
          <Navbar />
          <ToDoList />
        </main>
      </MainContext.Provider>
    </>
  )
}
